#!/usr/bin/env python3
"""Generate src/remote/assets/surge-meta.js from the pinned Surge sources.

The Remote UI receives every parameter's numeric control type, scene, group
and display description from patch_params.json (written by the plugin), but a
handful of Surge's name tables are compile-time constants that never reach a
parameter: the ctrltypes enum (so the page can reason about a type by name),
the modulation source names, the oscillator, FX and LFO type names, the FX slot
names. They are read out of the submodule at exactly the commit the plugin was
built from, so page and plugin cannot disagree.

    python3 src/tools/gen_surge_meta.py
"""
import json, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC = os.path.join(ROOT, "src/dsp/surge/src/common")
OUT = os.path.join(ROOT, "src/remote/assets/surge-meta.js")

def read(rel): return open(os.path.join(SRC, rel), encoding="utf-8").read()

def enum_names(text, name, prefix):
    m = re.search(r"enum\s+%s\b[^{]*\{(.*?)\}" % name, text, re.S)
    assert m, name
    body = re.sub(r"//.*", "", m.group(1))
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
    names = []
    for tok in body.split(","):
        tok = tok.strip()
        if not tok: continue
        ident = tok.split("=")[0].strip()
        if ident.startswith(prefix): names.append(ident)
    return names

def string_table(text, name):
    m = re.search(r"%s\s*\[[^\]]*\](?:\s*\[[^\]]*\])?\s*=\s*\{(.*?)\};" % re.escape(name), text, re.S)
    assert m, name
    return re.findall(r'"((?:[^"\\]|\\.)*)"', m.group(1))

param_h = read("Parameter.h")
storage_h = read("SurgeStorage.h")
mods_h = read("ModulationSource.h")

ctrltypes = enum_names(param_h, "ctrltypes", "ct_")
modsources = enum_names(mods_h, "modsources", "ms_")
lfotypes = enum_names(storage_h, "lfo_type", "lt_") or enum_names(storage_h, "LFOType", "lt_")

meta = {
    "surge_commit": open(os.path.join(ROOT, ".git/modules/src/dsp/surge/HEAD")).read().strip() if os.path.exists(os.path.join(ROOT, ".git/modules/src/dsp/surge/HEAD")) else "",
    "ctrltypes": ctrltypes,
    "modsources": modsources,
    "modsource_names": string_table(mods_h, "modsource_names"),
    "modsource_names_button": string_table(mods_h, "modsource_names_button"),
    "osc_type_names": string_table(storage_h, "osc_type_names"),
    "fx_type_names": string_table(storage_h, "fx_type_names"),
    "fx_type_shortnames": string_table(storage_h, "fx_type_shortnames"),
    "fxslot_names": string_table(storage_h, "fxslot_names"),
    "fxslot_shortnames": string_table(storage_h, "fxslot_shortnames"),
    "lt_names": string_table(storage_h, "lt_names"),
    "lfo_types": lfotypes,
    "control_groups": ["GLOBAL", "", "OSC", "MIX", "FILTER", "ENV", "LFO", "FX"],
    "display_types": ["Custom", "LinearWithScale", "ATwoToTheBx", "Decibel", "DelegatedToFormatter"],
    "display_features": {
        "kHasCustomMinString": 1, "kHasCustomMaxString": 2, "kHasCustomDefaultString": 4,
        "kHasCustomMinValue": 8, "kHasCustomMaxValue": 16, "kUnitsAreSemitonesOrKeys": 32,
        "kScaleBasedOnIsBiPolar": 64, "kAllowsTuningFractionTypein": 128,
        "kAllowsModulationsInNotesAndCents": 256, "kSwitchesFromSecToMillisec": 512,
        "kAllowsLinearFractionTypein": 1024,
    },
}
# the enum ends with n_modsources, so the table is one longer than the ms_ names
assert len(meta["modsource_names"]) >= len(modsources), (len(meta["modsource_names"]), len(modsources))
assert len(meta["fxslot_names"]) == 16 and len(meta["fxslot_shortnames"]) == 16

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w") as f:
    f.write("/* GENERATED by src/tools/gen_surge_meta.py from the pinned Surge sources. DO NOT EDIT. */\n")
    f.write("window.SURGE_META = ")
    json.dump(meta, f, separators=(",", ":"), ensure_ascii=True)
    f.write(";\n")
print("wrote %s: %d ctrltypes, %d modsources, %d osc types, %d fx types, %d lfo types" % (
    os.path.relpath(OUT, ROOT), len(ctrltypes), len(modsources), len(meta["osc_type_names"]), len(meta["fx_type_names"]), len(meta["lt_names"])))
